# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-python-with-github-actions

name: Python application

on:
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python 3.9
      uses: actions/setup-python@v2
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Test
      run: ./run_test.sh
    - name: Extract branch name
      shell: bash
      run: echo "##[set-output name=branch;]$(echo ${GITHUB_REF#refs/heads/})"
      id: extract_branch
    - name: 🚀 Upload results
      uses: JamesIves/github-pages-deploy-action@4.1.3
      with:
        BRANCH: ${{ steps.extract_branch.outputs.branch }}-result
        FOLDER: res
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        CLEAN: true  # Automatically remove deleted files from the deploy branch
